version: '3.7'

services:
  nutstash:
    image: nutstash
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    user: '1000:node'
    restart: on-failure
    ports:
      - '4173:3000'
